config/routes.rb
Rails.application.routes.draw do

  resources :logins

  resources :parties

  resources :events

  resources :vouchers

  resources :users

end

app/models/login.rb
class Login < ActiveRecord::Base
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

#<<<<<<< HEAD
  

def login(login)
  @login = Login.find_by login: login

  if !@login.nil? 
    redirect_to :controller => 'events', :action => 'show'
  end
end

def loginshow
  end


#=======
#>>>>>>> 70f0baeac44ea162a881e99f9e527ffab02fc96b
  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:user_id, :login, :passwd)
    end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :passwd %><br>
    <%= f.text_field :passwd %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing Login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Logins</h1>

<table>
  <thead>
    <tr>
      <th>User</th>

      <th>Login</th>

      <th>Passwd</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.user_id %></td>

        <td><%= login.login %></td>

        <td><%= login.passwd %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

app/views/logins/loginshow.html.erb
    <% form_tag :action => :create do %>

      <%= label_tag :user, 'Username: ' %><br>
      <%= text_field_tag :user %><br>

      <%= label_tag :password, 'Password: ' %><br>
      <%= password_field_tag :password %><br>

      <%= submit_tag 'Login' %>

    <% end %>

app/views/logins/new.html.erb
<h1>New Login</h1>

<%= render 'form' %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @login.user_id %>
</p>

<p>

  <strong>Login:</strong>
  <%= @login.login %>
</p>

<p>
  <strong>Passwd:</strong>
  <%= @login.passwd %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>